### ISSUE TITLE
Logging in the final version of the tests is undesirable

### ISSUE THREAD

**Issue by Nps-rf** [labintsev/neuralnets#92]
#### Description:
The use of `print()` statements within the test methods is undesirable for the final version of our test suite. While logging can be helpful during development and debugging, it adds noise to the test results in a production environment and should be avoided.

#### Location:
- Files: 
  - `test1.py`
    - Class: `TestRandomMatrix`
    - Method: `test_uniform`
  - `test2.py`
    - Class: `TestSoftmaxLoss`
    - Methods: `testLoss2`, `testLoss10`

#### Steps to Reproduce:
1. Run the test suite for both `test1.py` and `test2.py`.
2. Observe that certain methods print values like KS, p-value, and loss to the console.

#### Expected Behavior:
The tests should run silently, logging results only if there are test failures or if logging is explicitly enabled through a testing framework.

#### Actual Behavior:
The methods print values irrespective of test success/failure, adding unnecessary output during test runs.

#### Suggested Fixes:
- Remove the `print()` statements for the final version of the test suite in both files.
- If logging is required for debugging, consider using Python's `logging` library and configure it to only output logs under specific conditions.
- Alternatively, utilize the features of the testing framework to capture and display logs only when a test fails.

#### Severity:
🟢 Low

#### Priority:
🟢 Low

#### Additional Notes:
None

**Comment by labintsev** [comment]
Thanks a lot for a such great issue, best practice! Note that we have no production environment, just education. Logs are important, but software engineering  not a subject of this course. Noise stuff have no matter for autograding script, so its ok for me.

**Comment by Nps-rf** [comment]
You're welcome, and thank you for the context! I understand that the primary purpose of these tests is educational and not meant for a production environment. Given that software engineering practices like logging are not the focus of this course, and that the logs don't interfere with autograding, I see why the current setup works for you.

**Closing this issue as it's not applicable in the given educational setting. Feel free to reopen if circumstances change.**

**Best regards.**
