### ISSUE TITLE
Update the "Useful Resources" Section in README.md

### ISSUE THREAD

**Issue by Nps-rf** [labintsev/neuralnets#97]
#### Description:
The "Useful Resources" section in the README.md file could benefit from additional high-quality materials. Specifically, it would be helpful to include links to educational content on convolutional neural networks and other advanced topics to help students gain a deeper understanding of the subject matter.

#### Location:
- File: `README.md`
- Section: "Useful Resources"

#### Suggested Additions:
1. A YouTube playlist offering comprehensive tutorials on various machine learning topics: [YouTube Playlist](https://www.youtube.com/playlist?list=PLfdVzZl6HHg9y9l6U5xUjqKS13rWoQPF4)
2. An in-depth article on Habr about convolutional neural networks: [Погружение в свёрточные нейронные сети](https://habr.com/ru/articles/458170/)

#### Steps to Implement:
1. Navigate to the "Useful Resources" section in the `README.md` file.
2. Add the suggested links with appropriate anchor text.

#### Expected Impact:
These additional resources will provide more comprehensive learning materials for students who are interested in deepening their understanding of convolutional neural networks and other advanced topics.

#### Severity:
🔵 Medium

#### Priority:
🔵 Medium

#### Additional Notes:
Both of the suggested resources are **in Russian**. This will be particularly beneficial for Russian-speaking students, allowing for a more nuanced understanding of the complex subject matter.

**Comment by labintsev** [comment]
Yep, PR it please
